### ISSUE TITLE
Support for unicode characters

### ISSUE THREAD

**Issue by lukewilliamboswell** [isaacvando/rtl#4]
A template with the following `中文 (繁體)` characters causes a panic. 

```
+ rtl -i ./templates -o ./Generated
INFO: Searching for templates in ./templates ...
INFO: Reading templates...
INFO: Compiling templates...
The program crashed with:

	There is a bug! I was unable to convert these bytes into a string: [228].

Here is the call stack that led to the crash:

	roc.panic

Optimizations can make this list inaccurate! If it looks wrong, try running without `--optimize` and with `--linker=legacy`
```

**Comment by isaacvando** [comment]
The reason this is happening is that right now the `text` parser just parses a single byte and converts it to utf8. This works fine when the input is only ascii, but when there is unicode, it will attempt to convert a byte to utf8 that isn't valid. This is also quite bad to be doing this for every single byte, so it will be very good to fix beyond just utf8.

The easiest thing to do would be to only convert the bytes to a Str after all the text nodes have been merged. However, a better solution would be to parse longer contiguous sections of text in one go. I think we can do this by parsing text as long as we don't run into `{{` or `{|` and then trying the other parsers first if either of those symbols do come up.

I will take a look at this.
